/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#00658c",
        "surface-container-high": "#e4e9ed",
        "secondary": "#2b6486",
        "tertiary": "#4f5d72",
        "outline-variant": "#bec8d0",
        "inverse-on-surface": "#ecf1f5",
        "surface-variant": "#dee3e7",
        "on-error": "#ffffff",
        "inverse-primary": "#80d0ff",
        "primary-fixed": "#c5e7ff",
        "error-container": "#ffdad6",
        "secondary-container": "#a3d8ff",
        "surface-container-low": "#eff4f8",
        "surface-bright": "#f5fafe",
        "surface-dim": "#d5dbdf",
        "primary": "#006388",
        "on-tertiary": "#ffffff",
        "on-surface": "#171c1f",
        "on-background": "#171c1f",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#67758c",
        "primary-container": "#007dac",
        "outline": "#6f7880",
        "background": "#f5fafe",
        "surface-container-highest": "#dee3e7",
        "on-secondary-container": "#255f81",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fcfcff",
        "on-primary": "#ffffff",
        "inverse-surface": "#2c3134",
        "error": "#ba1a1a",
        "surface": "#f5fafe",
        "on-surface-variant": "#3f484f",
        "on-error-container": "#93000a",
        "surface-container": "#e9eef2",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
